export const collectibleToImageMap: Record<string, string> = {
  // Skullpanda - Warmth
  "skullpanda-warmth-1": "/images/Skullpanda/Warmth/1.jpg",
  "skullpanda-warmth-2": "/images/Skullpanda/Warmth/2.jpg",
  "skullpanda-warmth-3": "/images/Skullpanda/Warmth/3.jpg",
  "skullpanda-warmth-4": "/images/Skullpanda/Warmth/4.jpg",
  "skullpanda-warmth-5": "/images/Skullpanda/Warmth/5.jpg",
  "skullpanda-warmth-6": "/images/Skullpanda/Warmth/6.jpg",
  "skullpanda-warmth-7": "/images/Skullpanda/Warmth/7.jpg",
  "skullpanda-warmth-8": "/images/Skullpanda/Warmth/8.jpg",
  "skullpanda-warmth-9": "/images/Skullpanda/Warmth/9.jpg",
  "skullpanda-warmth-10": "/images/Skullpanda/Warmth/10.jpg",
  "skullpanda-warmth-11": "/images/Skullpanda/Warmth/11.jpg",
  "skullpanda-warmth-12": "/images/Skullpanda/Warmth/12.jpg",

  // Skullpanda - The Sound
  "skullpanda-the-sound-1": "/images/Skullpanda/The Sound/1.jpg",
  "skullpanda-the-sound-2": "/images/Skullpanda/The Sound/2.jpg",
  "skullpanda-the-sound-3": "/images/Skullpanda/The Sound/3.jpg",
  "skullpanda-the-sound-4": "/images/Skullpanda/The Sound/4.jpg",
  "skullpanda-the-sound-5": "/images/Skullpanda/The Sound/5.jpg",
  "skullpanda-the-sound-6": "/images/Skullpanda/The Sound/6.jpg",
  "skullpanda-the-sound-7": "/images/Skullpanda/The Sound/7.jpg",
  "skullpanda-the-sound-8": "/images/Skullpanda/The Sound/8.jpg",
  "skullpanda-the-sound-9": "/images/Skullpanda/The Sound/9.jpg",
  "skullpanda-the-sound-10": "/images/Skullpanda/The Sound/10.jpg",
  "skullpanda-the-sound-11": "/images/Skullpanda/The Sound/11.jpg",
  "skullpanda-the-sound-12": "/images/Skullpanda/The Sound/12.jpg",
  "skullpanda-the-sound-13": "/images/Skullpanda/The Sound/13.jpg",

  // Skullpanda - The Paradox
  "skullpanda-the-paradox-1": "/images/Skullpanda/The Paradox/1.jpg",
  "skullpanda-the-paradox-2": "/images/Skullpanda/The Paradox/2.jpg",
  "skullpanda-the-paradox-3": "/images/Skullpanda/The Paradox/3.jpg",
  "skullpanda-the-paradox-4": "/images/Skullpanda/The Paradox/4.jpg",
  "skullpanda-the-paradox-5": "/images/Skullpanda/The Paradox/5.jpg",
  "skullpanda-the-paradox-6": "/images/Skullpanda/The Paradox/6.jpg",
  "skullpanda-the-paradox-7": "/images/Skullpanda/The Paradox/7.jpg",
  "skullpanda-the-paradox-8": "/images/Skullpanda/The Paradox/8.jpg",
  "skullpanda-the-paradox-9": "/images/Skullpanda/The Paradox/9.jpg",
  "skullpanda-the-paradox-10": "/images/Skullpanda/The Paradox/10.jpg",
  "skullpanda-the-paradox-11": "/images/Skullpanda/The Paradox/11.jpg",
  "skullpanda-the-paradox-12": "/images/Skullpanda/The Paradox/12.jpg",
  "skullpanda-the-paradox-13": "/images/Skullpanda/The Paradox/13.jpg",

  // Hirono - Shelter
  "hirono-shelter-1": "/images/Hirono/Shelter/1.jpg",
  "hirono-shelter-2": "/images/Hirono/Shelter/2.jpg",
  "hirono-shelter-3": "/images/Hirono/Shelter/3.jpg",
  "hirono-shelter-4": "/images/Hirono/Shelter/4.jpg",
  "hirono-shelter-5": "/images/Hirono/Shelter/5.jpg",
  "hirono-shelter-6": "/images/Hirono/Shelter/6.jpg",
  "hirono-shelter-7": "/images/Hirono/Shelter/7.jpg",
  "hirono-shelter-8": "/images/Hirono/Shelter/8.jpg",
  "hirono-shelter-9": "/images/Hirono/Shelter/9.jpg",
  "hirono-shelter-10": "/images/Hirono/Shelter/10.jpg",
  "hirono-shelter-11": "/images/Hirono/Shelter/11.jpg",
  "hirono-shelter-12": "/images/Hirono/Shelter/12.jpg",
  "hirono-shelter-13": "/images/Hirono/Shelter/13.jpg",

  // Hirono - Reshape
  "hirono-reshape-1": "/images/Hirono/Reshape/1.jpg",
  "hirono-reshape-2": "/images/Hirono/Reshape/2.jpg",
  "hirono-reshape-3": "/images/Hirono/Reshape/3.jpg",
  "hirono-reshape-4": "/images/Hirono/Reshape/4.jpg",
  "hirono-reshape-5": "/images/Hirono/Reshape/5.jpg",
  "hirono-reshape-6": "/images/Hirono/Reshape/6.jpg",
  "hirono-reshape-7": "/images/Hirono/Reshape/7.jpg",
  "hirono-reshape-8": "/images/Hirono/Reshape/8.jpg",
  "hirono-reshape-9": "/images/Hirono/Reshape/9.jpg",
  "hirono-reshape-10": "/images/Hirono/Reshape/10.jpg",

  // Hirono - Echo
  "hirono-echo-1": "/images/Hirono/Echo/1.jpg",
  "hirono-echo-2": "/images/Hirono/Echo/2.jpg",
  "hirono-echo-3": "/images/Hirono/Echo/3.jpg",
  "hirono-echo-4": "/images/Hirono/Echo/4.jpg",
  "hirono-echo-5": "/images/Hirono/Echo/5.jpg",
  "hirono-echo-6": "/images/Hirono/Echo/6.jpg",
  "hirono-echo-7": "/images/Hirono/Echo/7.jpg",
  "hirono-echo-8": "/images/Hirono/Echo/8.jpg",
  "hirono-echo-9": "/images/Hirono/Echo/9.jpg",
  "hirono-echo-10": "/images/Hirono/Echo/10.jpg",
  "hirono-echo-11": "/images/Hirono/Echo/11.jpg",
  "hirono-echo-12": "/images/Hirono/Echo/12.jpg",
  "hirono-echo-13": "/images/Hirono/Echo/13.jpg",

  // Labubu - Exciting Macaron
  "labubu-exciting-macaron-1": "/images/Labubu/Exciting Macaron/1.jpg",
  "labubu-exciting-macaron-2": "/images/Labubu/Exciting Macaron/2.jpg",
  "labubu-exciting-macaron-3": "/images/Labubu/Exciting Macaron/3.jpg",
  "labubu-exciting-macaron-4": "/images/Labubu/Exciting Macaron/4.jpg",
  "labubu-exciting-macaron-5": "/images/Labubu/Exciting Macaron/5.jpg",
  "labubu-exciting-macaron-6": "/images/Labubu/Exciting Macaron/6.jpg",
  "labubu-exciting-macaron-7": "/images/Labubu/Exciting Macaron/7.jpg",
};
