export const BLINDBOX: Blindbox[] = [
    {
        characterName: "Skullpanda",
        serieName: "Warmth",
        serieNbr: 1,
        name: "Mind With the Wind",
    },
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 2, name: "Wandering",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 3, name: "Doodling",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 4, name: "The Day Off",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 5, name: "Recall the Past",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 6, name: "The Raining Day",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 7, name: "The Scent",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 8, name: "The Encounter",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 9, name: "Taste From the Memory",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 10, name: "Loosening",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 11, name: "Enjoy Oneself",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 12, name: "Chirping",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 2, name: "The Warmth",},
    {
        characterName: "Hirono",
        serieName: "Shelter",
        serieNbr: 1,
        name: "Candleholder",
    },
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 2, name: "Mantel Clock",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 3, name: "Poet",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 4, name: "Traffic Cone",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 5, name: "Fort",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 6, name: "Circus",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 7, name: "Cabin",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 8, name: "Birdy",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 9, name: "Alien",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 10, name: "Warrior",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 11, name: "Sunny Doll",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 12, name: "Birdcage",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 13, name: "Stuffed Bear",},
];