// ====== Blind Box Library Specifics =====

export const BLINDBOX: Blindbox[] = [
    {
        characterName: "Skullpanda",
        serieName: "Warmth",
        serieNbr: 1,
        name: "Mind With the Wind",
    },
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 2, name: "Wandering",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 3, name: "Doodling",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 4, name: "The Day Off",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 5, name: "Recall the Past",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 6, name: "The Raining Day",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 7, name: "The Scent",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 8, name: "The Encounter",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 9, name: "Taste From the Memory",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 10, name: "Loosening",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 11, name: "Enjoy Oneself",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 12, name: "Chirping",},
    {characterName: "Skullpanda", serieName: "Warmth", serieNbr: 2, name: "The Warmth",},
    {
        characterName: "Skullpanda",
        serieName: "The Sound",
        serieNbr: 1,
        name: "The Vigilance",
    },
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 2, name: "The Pensivness",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 3, name: "The Terror",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 4, name: "The Anger",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 5, name: "The Disgust",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 6, name: "The Ecstasy",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 7, name: "The Serenity",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 8, name: "The Admiration",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 9, name: "The Grief",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 10, name: "The Trust",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 11, name: "The Awe",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 12, name: "The Joy",},
    {characterName: "Skullpanda", serieName: "The Sound", serieNbr: 13, name: "The Equilibrium",},
    {
        characterName: "Skullpanda",
        serieName: "The Paradox",
        serieNbr: 1,
        name: "Out of the Mud",
    },
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 2, name: "The Jewel Cage",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 3, name: "Spin a Cocoon",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 4, name: "Being a Butterfly",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 5, name: "Diving in",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 6, name: "Flying High",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 7, name: "The Hold",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 8, name: "The Bond",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 9, name: "The External Echoes",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 10, name: "The Internal Dialogue",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 11, name: "The Asymmetrical Balance",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 12, name: "The Cyclical Path",},
    {characterName: "Skullpanda", serieName: "The Paradox", serieNbr: 13, name: "The Key",},
    {
        characterName: "Hirono",
        serieName: "Shelter",
        serieNbr: 1,
        name: "Candleholder",
    },
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 2, name: "Mantel Clock",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 3, name: "Poet",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 4, name: "Traffic Cone",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 5, name: "Fort",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 6, name: "Circus",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 7, name: "Cabin",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 8, name: "Birdy",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 9, name: "Alien",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 10, name: "Warrior",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 11, name: "Sunny Doll",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 12, name: "Birdcage",},
    {characterName: "Hirono", serieName: "Shelter", serieNbr: 13, name: "Stuffed Bear",},
    {
        characterName: "Hirono",
        serieName: "Reshape",
        serieNbr: 1,
        name: "Drowning",
    },
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 2, name: "Fading",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 3, name: "Costume",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 4, name: "Voyage",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 5, name: "Burst",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 6, name: "Paradise Lost",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 7, name: "Parasite",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 8, name: "Healing",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 9, name: "Woodcarving",},
    {characterName: "Hirono", serieName: "Reshape", serieNbr: 10, name: "Puppet",},
    {
        characterName: "Hirono",
        serieName: "Echo",
        serieNbr: 1,
        name: "Hiding Behind You",
    },
    {characterName: "Hirono", serieName: "Echo", serieNbr: 2, name: "Journey in the Rain",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 3, name: "Back Off",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 4, name: "Pieces of Memory",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 5, name: "Staying Up",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 6, name: "Daydreaming",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 7, name: "Get Lucky",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 8, name: "Breakout Plan",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 9, name: "Soul Connection",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 10, name: "Knight",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 11, name: "Caught You",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 12, name: "Eaten",},
    {characterName: "Hirono", serieName: "Echo", serieNbr: 13, name: "Never Growing Up",},
    {
        characterName: "Labubu",
        serieName: "Exciting Macaron",
        serieNbr: 1,
        name: "Sesame Bean",
    },
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 2, name: "Sea Salt Coconut",},
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 3, name: "Green Grape",},
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 4, name: "Lychee Berry",},
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 5, name: "Soymilk",},
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 6, name: "Toffee",},
    {characterName: "Labubu", serieName: "Exciting Macaron", serieNbr: 7, name: "Chestnut Cocoa",},
];